# Generated by Django 5.0.6 on 2024-06-17 18:28

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Class',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('class_name', models.CharField(max_length=20)),
                ('class_teacher', models.CharField(max_length=20)),
                ('class_size', models.SmallIntegerField()),
                ('class_rep', models.CharField(max_length=15)),
                ('class_enrollment', models.SmallIntegerField()),
                ('class_vision', models.CharField(max_length=20)),
                ('class_goal', models.CharField(max_length=50)),
                ('class_equipment', models.CharField(max_length=20)),
                ('class_lesson', models.PositiveBigIntegerField()),
            ],
        ),
    ]
